site_name: NetCDF95 documentation
site_url: https://www.lmd.jussieu.fr/~lguez/NetCDF95_site/index.html
repo_url: https://github.com/lguez/NetCDF95
site_author: Lionel GUEZ
nav:
   - Home: 'https://www.lmd.jussieu.fr/~lguez/'
   - 'index.md'
   - 'introduction.md'
   - 'installation.md'
   - 'Usage':
      - 'Usage/index.md'
      - 'Usage/datasets.md'
      - 'Usage/dimensions.md'
      - 'Usage/variables.md'
      - 'Usage/attributes.md'
      - 'Usage/errors.md'
   - 'changes.md'
markdown_extensions:
   - def_list
   - smarty
theme: readthedocs
